lib: {
  allSame = with lib; values:
    if tail values == []
      then true
    else if head values == head (tail values)
      then allSame (tail values)
    else false;

  join = with lib; sep: values:
    if values == []
      then ""
    else if tail values == []
      then head values
    else "${head values}${sep}${join sep (tail values)}";

  # based off https://stackoverflow.com/a/54505212
  recursiveMerge = with lib; attrList:
    let f = attrPath:
      zipAttrsWith (n: values:
        if tail values == []
          then head values
        else if all isList values
          then unique (concatLists values)
        else if all isAttrs values
          then f (attrPath ++ [n]) values
        else if allSame values
          then head values
        else abort "Values in ${join "." attrPath} can't be merged."
      );
    in f [] attrList;

  hardwareConfig = (
    # Do not modify this file!  It was generated by ‘nixos-generate-config’
    # and may be overwritten by future invocations.  Please make changes
    # to /etc/nixos/configuration.nix instead.
    { config, lib, pkgs, modulesPath, ... }:
    
    {
      imports =
        [ (modulesPath + "/installer/scan/not-detected.nix")
        ];
    
      boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "sd_mod" ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-intel" ];
      boot.extraModulePackages = [ ];
    
      fileSystems."/" =
        { device = "/dev/disk/by-uuid/a4ef7ef0-7ea6-46e4-8a5f-ec9cf5fe8f24";
          fsType = "ext4";
        };
    
      fileSystems."/boot" =
        { device = "/dev/disk/by-uuid/BFEA-950B";
          fsType = "vfat";
        };
    
      swapDevices =
        [ { device = "/dev/disk/by-uuid/04019ade-d0d4-40ff-a6f9-bf567ae3fce9"; }
        ];
    
      # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
      # (the default) this is the recommended approach. When using systemd-networkd it's
      # still possible to use this option, but it's recommended to use it in conjunction
      # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
      networking.useDHCP = lib.mkDefault true;
      # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
      # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;
    
      hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    
      # This option in deprecated in 23.05
      # high-resolution display
      #hardware.video.hidpi.enable = lib.mkDefault true;
    }
  );
}
